version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'the-first_app'
    restart: always
    ports:
      - '3000:80'

  json-server:
    image: 'ghcr.io/the-first-dance/the-first_json-server'
    container_name: 'the-first_json-server'
    restart: always
    ports:
      - '3401:3401'
    volumes:
      - ./server:/app/data
